---
# Kibana role defaults
kibana_version: "{{ kibana_version | default('9.1.3') }}"
kibana_data_dir: /var/lib/kibana
kibana_log_dir: /var/log/kibana
kibana_config_path: /etc/kibana/kibana.yml
kibana_user: kibana
kibana_group: kibana