apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kb-lab-cluster
  namespace: argocd # Ensure this matches your ArgoCD namespace
spec:
  project: default
  destination:
    namespace: elastic-stack
    server: https://kubernetes.default.svc
  sources:
    - repoURL: 'https://helm.elastic.co'
      targetRevision: '0.15.0'
      chart: 'eck-kibana'
      helm:
        valueFiles:
          - $values/k8s/lab-cluster/kb/kibana.yaml # Adjust to exact path in values repo
    - repoURL: git@github.com/wortmanb/homelab.git
      path: k8s/lab-cluster/kb
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {} # Optional: enable auto-sync
