apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  destination:
    namespace: external-secrets-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.external-secrets.io
      targetRevision: 0.10.0
      chart: external-secrets
      helm:
        valueFiles:
          - $values/k8s/external-secrets/values.yaml
    - repoURL: git@github.com:wortmanb/homelab.git
      path: k8s/external-secrets
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
