apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: friday-ui
  namespace: argocd
  annotations:
    # Argo Image Updater: automatically update image tags
    argocd-image-updater.argoproj.io/image-list: friday-ui=ghcr.io/wortmanb/friday-ui
    argocd-image-updater.argoproj.io/friday-ui.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    namespace: friday-ui
    server: https://kubernetes.default.svc
  source:
    path: k8s/friday-ui
    repoURL: https://github.com/hcbent/homelab.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
