apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kibana-ir
  namespace: elastic-stack
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`kibana.lab.thewortmans.org`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: lab-eck-kibana-kb-http
          port: 5601
  tls:
    secretName:  lab-eck-kibana-kb-http-ca-internal
