apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie
  namespace: default # Ensure this matches your ArgoCD namespace
spec:
  project: default
  destination:
    namespace: mealie
    server: https://kubernetes.default.svc
  sources:
    - repoURL: 'https://k8s-at-home.com/charts/'
      targetRevision: '5.1.2'
      chart: 'mealie'
      helm:
        valueFiles:
          - $values/k8s/mealie/values.yaml
    - repoURL: git@github.com/wortmanb/homelab.git
      path: k8s/mealie
      targetRevision: main
      ref: values
  syncPolicy:
#    syncOptions:
#      - CreateNamespace=true
    automated: {} # Optional: enable auto-sync
