apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-proxy-manager
  namespace: argocd
spec:
  project: default
  destination:
    namespace: nginx-proxy-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com/wortmanb/homelab.git
    path: k8s/nginx-proxy-manager
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
