apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd # Ensure this matches your ArgoCD namespace
spec:
  project: default
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  sources:
    - repoURL: 'https://mojo2600.github.io/pihole-kubernetes/'
      targetRevision: '2.31.0'
      chart: 'pihole'
      helm:
        valueFiles:
          - $values/k8s/pihole//pihole.yaml # Adjust to exact path in values repo
    - repoURL: git@github.com/wortmanb/homelab.git
      path: k8s/pihole
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {} # Optional: enable auto-sync
