apiVersion: v1
kind: Pod
metadata:
  name: iscsi-test-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: iscsi-volume
  volumes:
  - name: iscsi-volume
    persistentVolumeClaim:
      claimName: testpvc-iscsi
