apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd # Ensure this matches your ArgoCD namespace
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  sources:
    - repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
      path: .
      targetRevision: latest
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/k8s/prometheus/prometheus.yaml
    - repoURL: git@github.com/wortmanb/homelab.git
      path: k8s/prometheus
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {} # Optional: enable auto-sync
