apiVersion: v1
kind: Namespace
metadata:
  name: skooner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skooner
  namespace: skooner
  labels:
    app: skooner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skooner
  template:
    metadata:
      labels:
        app: skooner
    spec:
      containers:
      - name: skooner
        image: ghcr.io/skooner-k8s/skooner:stable
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
---
apiVersion: v1
kind: Service
metadata:
  name: skooner
  namespace: skooner
spec:
  selector:
    app: skooner
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skooner-ingress
  namespace: skooner
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web #, websecure
    traefik.ingress.kubernetes.io/router.tls: "false"
spec:
  rules:
  - host: skooner.lab.thewortmans.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: skooner
            port:
              number: 80
