---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skooner-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skooner-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # Use a more restrictive role if preferred
subjects:
- kind: ServiceAccount
  name: skooner-sa
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: skooner-sa-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: skooner-sa
type: kubernetes.io/service-account-token
