apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  destination:
    namespace: llm
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://helm.openwebui.com/
      targetRevision: 3.4.0
      chart: open-webui
      helm:
        valueFiles:
          - $values/llm/open-webui.yaml
    - repoURL: git@github.com/wortmanb/homelab.git
      path: llm
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}