apiVersion: v1
kind: ConfigMap
metadata:
  name: cerebro-config
  namespace: default
data:
  application.conf: |
    hosts = [
      {
        host = "http://elasticsearch.bwortman.us"
        name = "Homelab Cluster"
        auth = {
          type = "basic"
          username = "bret"
          password = "***REMOVED***"
        }
      }
    ]
    play.http.secret.key = "***REMOVED***"
    slick.dbs.default.profile = "slick.jdbc.H2Profile$"
    slick.dbs.default.db.driver = "org.h2.Driver"
    slick.dbs.default.db.url = "jdbc:h2:mem:cerebro;DB_CLOSE_DELAY=-1"
    slick.dbs.default.db.user = ""
    slick.dbs.default.db.password = ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro
  namespace: default
  labels:
    app: cerebro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebro
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - name: cerebro
        image: lmenezes/cerebro:latest
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /opt/cerebro/conf
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: cerebro-config
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro
  namespace: default
spec:
  type: NodePort
  ports:
  - port:
    targetPort: 9000
    nodePort: 30490
    protocol: TCP
  selector:
    app: cerebro
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: cerebro-ingress
#  namespace: default
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec: 
#  ingressClassName: nginx
#  rules:
#  - host: cerebro.lab.thewortmans.org
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: cerebro
#            port:
#              number: 9000
