---
# Pi-hole role defaults
# NOTE: pihole_webpassword should be retrieved from Vault in the playbook
# Vault path: secret/homelab/pihole/lab/credentials:webpassword
# This default is just a placeholder and should not be used in production
pihole_webpassword: "VAULT_SECRET_REFERENCE"
pihole_dns1: "1.1.1.1"
pihole_dns2: "8.8.8.8"
pihole_timezone: "America/New_York"

# Docker settings
pihole_image: "pihole/pihole:latest"
pihole_container_name: "pihole"
docker_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - docker.io
  - docker-compose
  - containerd

# Pi-hole directories
pihole_base_dir: /opt/pihole
pihole_directories:
  - "{{ pihole_base_dir }}"
  - "{{ pihole_base_dir }}/etc-pihole"
  - "{{ pihole_base_dir }}/etc-dnsmasq.d"
