apiVersion: v1
kind: Namespace
metadata:
  name: copyparty

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty
  namespace: copyparty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copyparty
  template:
    metadata:
      labels:
        app: copyparty
    spec:
      containers:
        - name: copyparty
          image: copyparty/ac:latest
          ports:
            - containerPort: 3923
          volumeMounts:
            - name: copyparty-data
              mountPath: /mnt/data
      volumes:
        - name: copyparty-data
          persistentVolumeClaim:
            claimName: copyparty-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-pvc
  namespace: copyparty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Ti

---
apiVersion: v1
kind: Service
metadata:
  name: copyparty
  namespace: copyparty
spec:
  type: NodePort
  selector:
    app: copyparty
  ports:
    - port: 3923
      targetPort: 3923
      nodePort: 30923   # pick a port in the allowed NodePort range (default: 30000â€“32767)

