---
apiVersion: v1
kind: Namespace
metadata:
  name: lab
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: lab
  namespace: lab
spec:
  version: 9.0.2
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: masters
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: freenas-iscsi-csi
    config:
      node.store.allow_mmap: false
      node.roles: ["master", "remote_cluster_client"]
  - name: hot
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Ti
        storageClassName: freenas-iscsi-csi
    config:
      node.store.allow_mmap: false
      node.roles: ["data_hot", "data_content", "remote_cluster_client"]
  - name: frozen
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Ti
        storageClassName: freenas-iscsi-csi
    config:
      node.store.allow_mmap: false
      node.roles: ["data_frozen", "remote_cluster_client"]
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: lab
  namespace: lab
spec:
  version: 9.0.2
  count: 1
  elasticsearchRef:
    name: lab
    namespace: lab
  http:
    service:
      metadata:
        annotations:
          metallb.universe.tf/address-pool: default
          metallb.universe.tf/allow-shared-ip: "true"
      spec:
        type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: lab
spec:
  rules:
  - host: kibana.lab.thewortmans.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lab-kb-http
            port:
              number: 5601 # Adjust if your service uses a different port
