apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
  namespace: elastic-stack
type: Opaque
stringData:
  s3.client.default.access_key: AKIAYW2UULNFD3N4MKWN
  s3.client.default.secret_key: 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
