---
- name: Setup host with basic configuration
  hosts: all
  become: true
  gather_facts: false
  vars:
    install_qemu_agent: true
    basic_host_setup: true
    setup_dotfiles: true

  roles:
    - proxmox_vm