---
# Security updates configuration tasks
- name: Configure automatic security updates
  apt:
    name: unattended-upgrades
    state: present
  when: ansible_facts['os_family'] == "Debian" and enable_unattended_upgrades

- name: Configure unattended upgrades
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    backup: yes
  when: ansible_facts['os_family'] == "Debian" and enable_unattended_upgrades