apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: friday-ui
  namespace: friday-ui
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: friday-ui-websocket-headers@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: friday.lab.thewortmans.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: friday-ui
                port:
                  number: 80
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: friday-ui
                port:
                  number: 8081
