# NodePort service to expose CrowdSec LAPI to host-based bouncers
apiVersion: v1
kind: Service
metadata:
  name: crowdsec-lapi-external
  namespace: crowdsec
  labels:
    app.kubernetes.io/name: crowdsec
    app.kubernetes.io/component: lapi
spec:
  type: NodePort
  selector:
    k8s-app: crowdsec
    type: lapi
  ports:
    - name: lapi
      port: 8080
      targetPort: 8080
      nodePort: 30808
