csiDriver:
  name: "org.democratic.csi.iscsi"

storageClasses:
  - name: truenas-iscsi-ext4
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4
      zfsPool: tank
      zfsParentName: tank/k8s/zvols
    mountOptions:
      - noatime
  - name: truenas-iscsi-zfs
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      zfsPool: tank
      zfsParentName: tank/k8s/iscsi
      zfsShareProperties: "mountpoint=legacy"
    mountOptions:
      - noatime

volumeSnapshotClasses:
  - name: truenas-iscsi-snapshot
    parameters:
      zfsPool: tank
      zfsParentName: tank/k8s/snapshots

driver:
  config:
    driver: freenas-api-iscsi
    httpConnection:
      protocol: http
      host: 192.168.2.24 # e.g., 192.168.1.100
      port: 80
      apiKey: <TRUENAS_API_KEY>
      allowInsecure: true
    zfs:
      datasetParentName: tank/k8s # Parent for both zvols and datasets
      datasetProperties:
        compression: lz4
        atime: off
        snapdir: visible
    iscsi:
      targetPortal: 192.168.2.24:3260
      targetIqnPrefix: iqn.2005-10.org.freenas.ctl
      targetLun: 0
      targetExtentType: zvol # Default, overridden per storage class if needed
